# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [3]:
import numpy as np

## Task 1
- print version of numpy

In [5]:
print(np.__version__)

1.15.4


## Task 2
- create 1d vector of zeros of size 10

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Task 3
- create 1d vector filled with ones of size 10

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 4
- create 1d vector filled with ones of size 10,

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [17]:
10+np.arange(40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [28]:
arr = np.arange(10)
# arr = arr[::-1] 
np.flipud(arr)
# arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [33]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [34]:
np.ones(9).reshape((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [45]:
np.random.randint(9, size=(3,3))

array([[7, 3, 1],
       [5, 6, 6],
       [5, 1, 8]])

## Task 10
- create 3x3x3 array filled with random numbers

In [46]:
np.random.randint(27, size=(3,3,3))

array([[[ 5, 20, 22],
        [15,  7, 24],
        [ 8,  7,  3]],

       [[13, 16, 18],
        [20, 22, 22],
        [15,  6,  8]],

       [[14,  1, 24],
        [21,  5,  7],
        [12, 11,  4]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [54]:
arr = np.random.randint(101,size=(10,10))
print('Max : ', arr.max())
print("Min : ", arr.min())

('Max : ', 99)
('Min : ', 2)


## Task 12
- create a random 1d vector of size 30 and find average of them

In [57]:
np.random.randint(100,size=(30)).mean()

50.2

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [66]:
arr = np.zeros(25).reshape((5,5))
arr[0] = 1
arr[4] = 1
arr[:,0]=1
arr[:,4]=1
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [51]:
arr = [[1,0],[0,1]]

ValueError: operands could not be broadcast together with shapes (2,2) (3,1) 

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [38]:
arr = [[1,0],[0,1]]
np.tile(arr,(4,4))
# help(np.tile)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [34]:
def get_array(size_of_array, max_int=100):
    return np.random.randint(max_int, size=size_of_array)

a = get_array((5,3))
b = get_array((3,2))
# print(a)
# print(b)
np.multiply.outer(a,b)


array([[[[3864, 4600],
         [2484, 5704],
         [7544, 3496]],

        [[ 252,  300],
         [ 162,  372],
         [ 492,  228]],

        [[1092, 1300],
         [ 702, 1612],
         [2132,  988]]],


       [[[3066, 3650],
         [1971, 4526],
         [5986, 2774]],

        [[3024, 3600],
         [1944, 4464],
         [5904, 2736]],

        [[4158, 4950],
         [2673, 6138],
         [8118, 3762]]],


       [[[ 126,  150],
         [  81,  186],
         [ 246,  114]],

        [[1134, 1350],
         [ 729, 1674],
         [2214, 1026]],

        [[3024, 3600],
         [1944, 4464],
         [5904, 2736]]],


       [[[1932, 2300],
         [1242, 2852],
         [3772, 1748]],

        [[ 420,  500],
         [ 270,  620],
         [ 820,  380]],

        [[ 168,  200],
         [ 108,  248],
         [ 328,  152]]],


       [[[ 714,  850],
         [ 459, 1054],
         [1394,  646]],

        [[ 126,  150],
         [  81,  186],
         [ 246,  114]],

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

## Task 21
- create random 13x13 matrix, replace maximal element to zero

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

## Task 23
- create an array of random `float` numbers and convert it to `int`

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element